name: architecture_template
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8 #config
  easy_logger: ^0.0.2 # utility
  equatable: ^2.0.7 # core
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1 # state management
  flutter_svg: ^2.1.0
  google_fonts: ^6.3.0 # utility
  json_annotation: ^4.9.0 # config
  kartal: ^4.1.0 # utility
  logger: ^2.6.0 # utility
  vexana: ^5.0.3 # network

  widgets:
    path: module/widgets

  gen:
    path: module/gen
  
# dependecy_overrides:
#   cupertino_icons: ^1.0.7

dev_dependencies:

  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  # vb10:
  #   git:
  #     url: https://github.com/VB-CORE/life_client
  very_good_analysis: ^7.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/translations/



